version: "3.2"
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-service
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net

  postgres:
    container_name: postgres-service
    ports: 
        - "5432:5432"
    image: postgres
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=sheila
    networks:
        - rabbitmq_go_net
   
  postgres-fila:
    container_name: postgres-service-fila
    ports: 
        - "5433:5432"
    image: postgres
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=sheila
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge